### ISSUE TITLE
Create a design for the profile page

### ISSUE THREAD

**Issue by jcreek** [jcreek/LivingDexTracker#39]
This should be in the form of a wireframe and should include all components currently in the page. This will then be used for styling the page itself. 

<img width="1065" alt="image" src="https://github.com/jcreek/LivingDexTracker/assets/8179928/da6df81d-9a54-4327-9eec-3bef33b797fb">

**Comment by AmberPM** [comment]
![wireframe profile](https://github.com/jcreek/LivingDexTracker/assets/141347578/512f76ba-6446-4fad-ab8d-9fa2530dbddd)

**Comment by jcreek** [comment]
Looks great :)
